# Exercise 2 - Introduction to Python, Numpy & Pandas

In this session we will start of with a few repetition exercises. Please ask questions! Since these concepts are very important for the upcoming weeks. No matter whether it is about small details or a concept as a whole! :-)

As we get more and more comfortable with basic operations in Python we will start introducing libraries namely, Numpy and Pandas. 
A library is a reusable chunk of code that you may want to include in your programs/projects. The community generated code for common problems and provides them as functions in libraries for you. 

You can think of these functions just like the built in ones in Python. If you want to know how many characters a string has you could either write a loop and add to a variable with each character you looped over --> quite a lot of work so you would be using the len() function. Similar to the len() function numpy and pandas provide tricks that will make your life a lot easier!
We will introduce some functionalities of the libraries as we go! :) (there are too many to introduce them all)

If you are interested in what libraries are out there, here is a list with many common ones: 
https://data-flair.training/blogs/python-libraries/

### Credits

This tutorial was inspired by various other websites and resources (accessed: 12.3.2020):
- https://data-flair.training/blogs/python-libraries/
- https://towardsdatascience.com/top-python-libraries-numpy-pandas-8299b567d955
- https://github.com/zhiyzuo/python-tutorial
- https://www.practicepython.org/

- https://www.w3schools.com/python/default.asp

- https://www.tutorialspoint.com/python/index.htm


In [10]:
print('Let\'s get started!') # remember the escape character '\' ! :)

Let's get started!


Exercise 1:
Take a list, say for example this one:

a = [2, 34, 542, 2, 45, 67, 85, 457, 1]

and write a program that prints out all the elements of the list that are less than 5.

In [11]:
# Exercise 1
a = [2, 34, 542, 2, 45, 67, 85, 457, 1]

In [12]:
# Here we go :)
# remember how a for loop works or go look it up in last weeks assignment 
[i for i in a if i < 5]

[2, 2, 1]

In [13]:
# Exercise 2: 
# Now we have two lists
keys = ['Soccer player', 'Basketball player', 'Volleyball player']
values  =['Lionel Messi', 'Kobe Bryant', 'Bruno Rezende']
print(len(keys))

3


Remember the data type "dictionary" we intorduced last time?
Let's try to put the information from the two lists into one dictionary. 
You have three keys and three values. Join them into one dictionary.

Tipps:

- This creates an empty dictionary: dict()

- You will have to use your knowledge about indexing!

Advanced:
For those of you with some python knowledge. Write a loop that fills the dicitonary. :)

In [14]:
# Exercise 2: Give it a try!
dict_exercise = dict()
for x in range(len(keys)):
    dict_exercise[keys[x]] = values[x]
    
print(dict_exercise)
    

{'Soccer player': 'Lionel Messi', 'Basketball player': 'Kobe Bryant', 'Volleyball player': 'Bruno Rezende'}


Exercise 3:

Take two lists, say for example these two:

  a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
  
  b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  
and write a program that returns a list that contains only the elements that are common between the lists (without duplicates).
Make sure your program works on two lists of different sizes.

In [15]:
# Exercise 3 :)
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
common = []
# Hint the "in" function comes in handy --> check it in the documentation
for i in range(len(b)):
    for j in range(len(a)):
        if a[j] == b[i]:
            if a[j] not in common:
                common.append(a[j])

print(common)


[1, 2, 3, 5, 8, 13]


Now that we have briefly repeated the basics that we learnd last time, we will now turn to Numpy and Pandas.
In case you feel like you want to practive more go and visit Datacamp or check the links in the cell at the top. 




# Numpy

What is it? A library for Python, NumPy lets you work with huge, multidimensional matrices and arrays. Along with that, it provides a gamut of high-level functions to perform mathematical operations on these structures.
The term ‘Numpy’ is a portmanteau of the words ‘NUMerical’ and ‘PYthon’.

Since Numpy is is an external library we have to install and import it.

The installation is already done (if Anaconda is this time installed as it is supposed to). You can easily manage the packages in Anaconda for your own laptop and download it.




In [17]:
# we need to import it in each script once (usually at the top)

import numpy as np 

# Note: the "as np" part is not necessary but makes it's use easier afterwards :)

Now numpy is imported and we can make use of it. In general we call a numpy function by typing: np.SOMEFUNCTION (i.e. np.array)

Let's see what numpy can do! 

### NumPy ndarray

This is one of the most important features of numpy. ndarray is an n-dimensional array, a grid of values of the same kind. A tuple of nonnegative integers indexes this array. An array’s rank is its number of dimensions. Let’s take a few examples.



In [ ]:
a=np.array([1,2,3]) # this is a numpy array basically looks like a list you apply the array function to 
a

array([1, 2, 3])

In [ ]:
# Here an illustration:
a = [1, 2, 3]
print(a)
print(type(a))

a=np.array([1,2,3])
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


The shape of your array:

In [ ]:
a.shape # get the shape of your array

(3,)

In [ ]:
# Get values out of your array
a[0],a[2] # the 1st and 3rd value - remember python's indexing starts with 0

(1, 3)

In [ ]:
# assign values to individual array positions
a[1] = 5
a

array([1, 5, 3])

As you can see, the array’s shape is (3,). What happens when we build an array of more than one dimension? Let’s see.

In [ ]:
# 2 dimensions
b=np.array([[2,7,9],[5,1,3]])
b

array([[2, 7, 9],
       [5, 1, 3]])

In [ ]:
# Access individual values in 2d arrays
b[0,1]

7

In [ ]:
# Your exercise: Get the shape of b

b.shape

(2, 3)

In [ ]:
# The size of an array
b.size # number of entries in your array

6

Other important functions that Numpy provides:

In [ ]:
np.arange(7) #This is like range in Python

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.random.random((3,3)) #Fills in random values

array([[0.10042685, 0.78324163, 0.17730931],
       [0.70604881, 0.18628866, 0.93943503],
       [0.11081442, 0.24089195, 0.20844427]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Your exercise: Try to get the same thing with zeros
np.full(3,0)


array([0, 0, 0])

In [ ]:
# Your exercise: Does it work with other numbers? For example with number 4?
np.full(3,4)


array([4, 4, 4])

In [ ]:
# Get a matrix with constants like 2s
np.full((3,2),2) # Matrix of constants - first you indicate the shape afterwards the number

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
# This is a good opportunity to compare this array to the previous ones
a = np.zeros((2,3))
b = np.zeros((3,2))

In [ ]:
a # make sure you understand how python counts rows and numbers! :)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Functions of NumPy Arrays

Let’s take a look at some things that we can do with an array and what more we can find out about it.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = a.reshape(3,2) # reshape your array
a

array([[1, 2],
       [3, 4],
       [5, 6]])

Python always starts with the rows followed by the columns.
This is also very important when you try to access individual values, rows or columns.


In [ ]:
a.ndim # get the number of dimensions

2

### Numpy Array Indexing

In [ ]:
# If you remember Python's indexing, 
# that you start with rows following the columns
# and start counting with 0 there is little that can go wrong!
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[:2,1:3]
b

array([[2, 3],
       [5, 6]])

In [ ]:
# Your exercise: Try to reverse the row order of a
# so that the first row contains 7, 8, 9 and the last 1, 2, 3
a[::-1]



array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### Integer indexing
It is possible to create an array from another.

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
a[[0,1,2],[0,1,0]] #Prints elements at [0,0], [1,1], and [2,0]

array([1, 4, 5])

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [ ]:
a[np.arange(4), b] # b are the indexes that will be picked out of a

array([ 1,  6,  7, 11])

### Mathematical Functions on Arrays in NumPy

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.add(a,b) #a+b does the same
# Pay attention that the individual values are added to another elementwise!

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.subtract(a,b) #Same as a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [ ]:
np.multiply(a,b) #a*b works too (elementwise)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
np.divide(a,b) #Same as a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
a=np.array([[1,2],[3,4]])
np.sum(a)

10

In [ ]:
np.sum(a,axis=0)

array([4, 6])

In [ ]:
np.sum(a,axis=1)

array([3, 7])

In [ ]:
# Your exercise: Transpose a matrix turns rows into columns and columns into rows, syntax: nparray.T
# create a matrix and try it!
a = np.array([[1, 2], [3, 4]])
a.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
# Find the max value in an array
a.max()

4

In [ ]:
# You have to be aware that matrix multiplication and elementwise multiplication are different things!
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

C = A * B # elementwise
print(C)
D = A @ B # matrixproduct
print(D)
E = A.dot(B) # matrixproduct
print(E)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [ ]:
# Flatten an array into a 1-D shape
A

array([[1, 1],
       [0, 1]])

In [ ]:
A.flatten()

array([1, 1, 0, 1])

### More resources

That concludes the Numpy intro for now. 
Here you can find additional resources: 

- https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

- https://www.datacamp.com/community/tutorials/python-numpy-tutorial?utm_source=adwords_ppc&utm_campaignid=898687156&utm_adgroupid=48947256715&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=332602034349&utm_targetid=aud-299261629574:dsa-473406585115&utm_loc_interest_ms=&utm_loc_physical_ms=9062727&gclid=Cj0KCQjwu6fzBRC6ARIsAJUwa2Rp566ZsH43OoRGjj64-a54C55IJgfwfuCTb-DBg9Kuz0YpGT36tngaAlH4EALw_wcB


# Pandas
Pandas is an open-source library built on top of numpy providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. It allows for fast analysis and data cleaning and preparation. It excels in performance and productivity. It can work with data from a wide variety of sources. Pandas is suited for many different kinds of data: tabular data, time-series data, arbitrary matrix data with row and column labels, and Any other form of observational/statistical data sets. 

Here a Pandas cheatsheet:

- https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

Just like numpy it is already installed, but has to be imported:

In [ ]:

import pandas as pd

Let's get some data to manipulate to better understand Pandas. There is a csv file with the famous iris (flowers) dataset on moodle for you to download. Download it and then upload it to Jupyter the same way you uploaded the notebook. It also works if the iris.csv is in the same directory as your jupiter notebook file.

In [18]:
# Let's import the iris.csv into a pandas DataFrame and see the first functionality of pandas
iris = pd.read_csv('data/healthcare-dataset-stroke-data.csv')  

In [19]:
type(iris) # The Dataframe is the core structure in pandas

pandas.core.frame.DataFrame

### Dataframe
A DataFrame is an essential data structure within pandas. It lets us deal with data in a tabular fashion. The rows are observations and columns are variables.
We have the following syntax for this-

pandas.DataFrame( data, index, columns, dtype, copy)

You need to mention the data, index and columns value to generate a DataFrame. Data should be at least two-dimensional, index will be the row name and columns values for the columns.

In [20]:
# But let's explore our data a bit first and get to know some useful functions.
iris.columns # let's see what the categories are.

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [21]:
# So far we know what the columns contain
# Let's get the shape of our dataframe
iris.shape

(5110, 12)

In [22]:
# number of rows
iris.shape[0]

5110

In [23]:
# number of columns 
iris.shape[1]

12

In [24]:
# Let's look at the first few lines
iris.head(5)

# type in "iris" to get the full dataset

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [25]:
iris

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [26]:
# We can also create a dataframe ourselves like the following: 
df=pd.DataFrame({'company':['Amazon','Apple','Google','Facebook','Microsoft'],
    'CEO':['Jeff Bezos','Tim Cook','Sundar Pichai','Mark Zuckerberg','Satya Nadella'],
    'Founded':[1994,1976,1998,2004,1975]})

df

company              CEO  Founded
0     Amazon       Jeff Bezos     1994
1      Apple         Tim Cook     1976
2     Google    Sundar Pichai     1998
3   Facebook  Mark Zuckerberg     2004
4  Microsoft    Satya Nadella     1975

Now this indexes the dataframe as integers starting at 0. But we can put labels on these. Let’s see how we can index it based on which company came first.

In [27]:
df.index=['Third','Second','Fourth','Fifth','First']
df

company              CEO  Founded
Third      Amazon       Jeff Bezos     1994
Second      Apple         Tim Cook     1976
Fourth     Google    Sundar Pichai     1998
Fifth    Facebook  Mark Zuckerberg     2004
First   Microsoft    Satya Nadella     1975

In [28]:
# Let's say you only want to know about the CEO of the companys
df['CEO'] # df.CEO would do the same thing :)

# Your Exercise: Try to get the species from the iris dataset 
iris['variety']


KeyError: 'variety'

In [29]:
# The just used command returns a series
print(type(df['CEO']))
print(type(df.CEO))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


Check the pandas documentation to learn more about series

(visited 14.3.2020)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

In [ ]:
# To make it a dataframe we can use:
df[['CEO']]

CEO
Third        Jeff Bezos
Second         Tim Cook
Fourth    Sundar Pichai
Fifth   Mark Zuckerberg
First     Satya Nadella

In [ ]:
type(df[['CEO']])

pandas.core.frame.DataFrame

In [ ]:
# Similarly to Numoy Arrays we can also slice Dataframes
df[0:3]

company            CEO  Founded
Third   Amazon     Jeff Bezos     1994
Second   Apple       Tim Cook     1976
Fourth  Google  Sundar Pichai     1998

In [ ]:
# Your exercise: Now try to get the first 10 rows of the iris data set
iris[0:10]


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

### More data selection operations

Using loc and iloc, you can select certain rows in a data set. loc uses string indices; iloc uses integers.



In [ ]:
# Before looking at the loc and iloc function let us have a look at the dataframe again:
df

company              CEO  Founded
Third      Amazon       Jeff Bezos     1994
Second      Apple         Tim Cook     1976
Fourth     Google    Sundar Pichai     1998
Fifth    Facebook  Mark Zuckerberg     2004
First   Microsoft    Satya Nadella     1975

In [ ]:
df.loc[['Second','Fifth']]

company              CEO  Founded
Second     Apple         Tim Cook     1976
Fifth   Facebook  Mark Zuckerberg     2004

In [ ]:
df.iloc[3]

company           Facebook
CEO        Mark Zuckerberg
Founded               2004
Name: Fifth, dtype: object

In [ ]:
# Getting more than one column-
df.iloc[:,1:4]

CEO  Founded
Third        Jeff Bezos     1994
Second         Tim Cook     1976
Fourth    Sundar Pichai     1998
Fifth   Mark Zuckerberg     2004
First     Satya Nadella     1975

### Sorting data

We can use the function sort_values()

In [ ]:
iris.sort_values('sepal.length',ascending=False)

sepal.length  sepal.width  petal.length  petal.width    variety
131           7.9          3.8           6.4          2.0  Virginica
135           7.7          3.0           6.1          2.3  Virginica
122           7.7          2.8           6.7          2.0  Virginica
117           7.7          3.8           6.7          2.2  Virginica
118           7.7          2.6           6.9          2.3  Virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     Setosa
42            4.4          3.2           1.3          0.2     Setosa
38            4.4          3.0           1.3          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
13            4.3          3.0           1.1          0.1     Setosa

[150 rows x 5 columns]

In [ ]:
# Dropping rows and columns
iris.drop('variety',axis=1)

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# Get index of values that fulfill specific conditions. Index of entries with sepal length equal to 5.4
indexNames = iris[ iris['sepal.length'] == 5.4 ].index
indexNames

Int64Index([5, 10, 16, 20, 31, 84], dtype='int64')

# Exercises

This concludes for the introduction to Pandas and Numpy.
You should take some time to practice and read up on the concepts. Since programming is learnt the best by running into problems and solving them step by step. 

We will do some more exercises here based on assignments from: 

https://www.w3resource.com/index.php

### Numpy exercises

In [ ]:
# Exercise 4: Write a NumPy program to create an array of 10 zeros, then one of 10 ones, and finally one of 10 fives.
np.zeros(10)
np.ones(10)
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Exercise 5: Write a NumPy program to create a 3x3x3 array filled with random values between 0 and 1.
np.random.random((3,3,3))


array([[[0.68872594, 0.74538567, 0.76792231],
        [0.08082606, 0.58633339, 0.97741081],
        [0.83938336, 0.14299678, 0.90230541]],

       [[0.69502126, 0.47434204, 0.89616203],
        [0.55776378, 0.00128652, 0.98111754],
        [0.10193943, 0.0597897 , 0.18746847]],

       [[0.18787243, 0.2505101 , 0.9332981 ],
        [0.7059965 , 0.60263902, 0.17598864],
        [0.04978829, 0.10341973, 0.03563162]]])

In [ ]:
# Exercise 6: Write a NumPy program to create a 3x4 array and iterate over its entries and print them.
# Use the np.nditer() function
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")


Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

For more numpy exercises visit:

https://www.w3resource.com/python-exercises/numpy/index.php

### Pandas exercises

In [ ]:
# Exercise 7: Write a Python program that add, subtract, multiple and divide two Pandas Series. 
# Carried out one after the other.
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
print(ds1 + ds2)
print(ds1 - ds2)
print(ds1 * ds2)
print(ds1/ds2)


0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [ ]:
# Exercise 8: Write a Pandas program to select the specified columns and rows from a given data frame.
# Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']



For more Pandas exercises visit:

https://www.w3resource.com/python-exercises/pandas/index.php